[project]
name = "admision-instituto-educativo"
version = "0.1.0"
description = "Backend de gestión educativa y admisiones"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.5",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.2",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "psycopg2-binary>=2.9.12",
    "python-decouple>=3.8",
    "pymongo>=4.7.0",
    "gunicorn>=22.0",
]
