server {
    listen 80;
    server_name 143.244.157.1 macias-admisiones.uaeftt-ute.site;

    # Logs
    access_log /var/log/nginx/admision-instituto-educativo-access.log;
    error_log  /var/log/nginx/admision-instituto-educativo-error.log;

    # Static files (includes Django Admin CSS)
    location /static/ {
        alias /opt/admision-instituto-educativo/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # API requests via Gunicorn
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn-admision-instituto-educativo.sock;
        proxy_read_timeout 90;
        proxy_connect_timeout 90;
    }
}
